# Generated by Django 2.0.2 on 2018-03-01 14:14

from django.db import migrations, models
import django.db.models.deletion
import imagedump.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papillon_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=imagedump.models.image_save_location)),
                ('title', models.CharField(max_length=512)),
                ('upload_date', models.DateTimeField()),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='papillon_user.PapillonUser')),
            ],
        ),
    ]
