# Generated by Django 2.0.3 on 2018-03-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagedump', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
            ],
        ),
    ]
